# Generated by Django 4.0.5 on 2022-06-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_alter_post_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
