# Generated by Django 4.0.5 on 2022-06-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0009_alter_post_image_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='post-images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='static/images/default.png', upload_to='profile-images/'),
        ),
    ]
