# Generated by Django 4.0.5 on 2022-06-08 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0011_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pk']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
